# Generated by Django 4.0 on 2022-01-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_usercomment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
